"use strict";

const { DEFAULT_ENDSTONE_PACKAGE } = require("./options");

function printHelp() {
  console.log([
    "Usage:",
    "  node scripts/e2e-servers.js install [--target=all|java|endstone] [--java-count=2] [--endstone-count=2]",
    "  node scripts/e2e-servers.js launch  [--target=all|java|endstone] [--java-count=2] [--endstone-count=2] [--client=\"pnpm run test:live\"]",
    "  node scripts/e2e-servers.js launch  --target=java --java-count=2 --exit-after-client --client pnpm run test:live:shard",
    "  node scripts/e2e-servers.js launch  --target=java --exit-after-client --client-timeout-ms=600000 --client pnpm run test:live",
    "  node scripts/e2e-servers.js launch  --target=endstone --client pnpm run test:live",
    "  node scripts/e2e-servers.js launch  --target=endstone --world=superflat --endstone-packet-recorder",
    "  node scripts/e2e-servers.js launch  --target=endstone --world=superflat --endstone-scenario=craft-planks-and-place",
    `  node scripts/e2e-servers.js launch  --target=endstone --endstone-package=${DEFAULT_ENDSTONE_PACKAGE} --client pnpm run test:live`,
    "  node scripts/e2e-servers.js install --target=java --geyser-extension=astrox --geyser-extension=boar",
    "  node scripts/e2e-servers.js install --target=java --java-profiles=none,astrox,boar",
    "  node scripts/e2e-servers.js install --target=java --java-worlds=normal,superflat",
    "  node scripts/e2e-servers.js clean --scope=worlds",
    "  node scripts/e2e-servers.js clean --scope=logs",
    "  node scripts/e2e-servers.js cleanup-orphans [--dry-run] [--include-managed]",
    "",
    "Environment:",
    "  E2E_PAPER_VERSION       Paper Minecraft version, default latest",
    "  E2E_JAVA_BIN            Java executable used to launch Paper, default java",
    "  E2E_GEYSER_AUTH_TYPE    Geyser Java auth type, default offline for local bot tests",
    "  E2E_JAVA_PORT           Java server port, default 25565",
    "  E2E_GEYSER_PORT         Geyser Bedrock UDP port, default 19133",
    "  E2E_ENDSTONE_PORT       Endstone Bedrock UDP port, default 19132",
    "  E2E_JAVA_COUNT          Number of Java/Geyser instances, default 1",
    "  E2E_JAVA_PROFILES       Comma-separated Java plugin profiles, e.g. none,astrox,boar,astrox+boar",
    "  E2E_WORLD               World type for all instances: normal or superflat",
    "  E2E_JAVA_WORLDS         Comma-separated Java world types, e.g. normal,superflat",
    "  E2E_ENDSTONE_COUNT      Number of Endstone/BDS instances, default 1",
    "  E2E_ENDSTONE_WORLDS     Comma-separated Endstone world types, e.g. normal,superflat",
    `  E2E_ENDSTONE_PACKAGE    uv package spec, default ${DEFAULT_ENDSTONE_PACKAGE}`,
    "  E2E_ENDSTONE_PACKET_RECORDER  Set 1 to install the Endstone packet hook recorder",
    "  E2E_ENDSTONE_SCENARIO         Scenario id or JSON path under test/recorded-bds/scenarios",
    "  E2E_PACKET_RECORD_FILE        Recorder JSONL path, default logs/packet-recorder.jsonl under server cwd",
    "  E2E_PACKET_RECORDER_PACKET_IDS Comma-separated numeric packet IDs to record; empty records all",
    "  E2E_PACKET_RECORDER_PLAYERS    Comma-separated player names to record; empty records all players",
    "  E2E_PACKET_RECORDER_SPLIT_BY_PLAYER Set 1 to also write packet-recorder.<player>.jsonl files",
    "  E2E_GEYSER_EXTENSIONS   Comma-separated Geyser extensions: astrox, boar, github:owner/repo, or URL",
    "  E2E_AUTO_OP             Auto-op Java/Geyser players on join, default 1; set 0 to disable",
    "  E2E_CLIENT_RUN_INDEX    Set for client fan-out; 0-based shard index",
    "  E2E_CLIENT_RUN_TOTAL    Set for client fan-out; total client shards",
    "",
    "Interactive launch commands:",
    "  /client <client command>",
    "  /java <server command>",
    "  /java-1 <server command>",
    "  /endstone <server command>",
    "  /endstone-1 <server command>",
    "  /all <server command>",
    "  /quit",
    "",
    "Launch options:",
    "  --exit-after-client      Stop launched servers after the next client run exits and return its exit code",
    "  --client-timeout-ms=N    With --exit-after-client, stop servers and return 124 if the client times out",
    "  --client-stop-delay-ms=N Delay before stopping servers after client exit, default 2000",
    "  --server-ready-timeout-ms=N Delay before giving up on server readiness, default 120000",
    "  --client CMD            With multiple servers, runs one client process per server with scoped HOST/PORT/lock env",
    `  --endstone-package=SPEC Pin Endstone package spec, e.g. ${DEFAULT_ENDSTONE_PACKAGE}`,
    "  --endstone-packet-recorder Install an Endstone plugin that records PacketReceiveEvent/PacketSendEvent to JSONL",
    "  --endstone-packet-recorder-player=NAME Record packets only for the named player; repeatable/comma-separated",
    "  --endstone-packet-recorder-split-by-player Also write per-player recorder JSONL files",
    "  --endstone-scenario=ID_OR_PATH Run a stepped Endstone-only human recording scenario; enables recorder",
    "  --no-auto-op            Disable automatic Java/Geyser op-on-join",
    "",
    "Cleanup options:",
    "  --dry-run               For cleanup-orphans, report matching processes and stale locks without deleting",
    "  --include-managed       Also stop e2e server trees still owned by a launcher process",
    ""
  ].join("\n"));
}

module.exports = { printHelp };
